name: Action

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  print-messages:
    runs-on: ubuntu-latest

    env:
      MY_ENV_VARIABLE: Hello from env variable!

    steps:
      - name: Print environment variable
        run: echo "$MY_ENV_VARIABLE"

      - name: Print secret variable
        env:
          MY_SECRET_VARIABLE: "${{ secrets.MY_SECRET }}"
        run: echo "$MY_SECRET"
